### PR TITLE
#37: ft-seller-should-update-product

### PR DESCRIPTION
**Pull request by nili-alu**
#### What does this PR do?
A seller should be able to update a product's information 

#### Description of Task to be completed?
A seller should be able to modify the every single information about product, if update button in collection clicked a seller should be prompted with a form pre-filled with the existing info about product and modify them. after modifying he/she must click on update button on form to save the changes.

### a. 
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch ft-seller-update-product-37
npm i
npm run dev
```
### b. 
in browser on the opened url add ``` url/vendor``` example: ``` http://localhost:5173/product ```
#### What are the relevant pivotal tracker/Trello stories?
Trello [[Link](https://trello.com/c/pFDY8MrM/37-a-seller-should-be-able-to-update-an-product-item-from-their-collection)](#37)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Review by NTElissa — APPROVED** [review]
GOOD PROGRESS

**Review by kagaba-etienne — APPROVED** [review]
Good job!

**Review by vanessa-abewe — APPROVED** [review]

**Review by yobuir — APPROVED** [review]
nice work

**Review by chanceDira — APPROVED** [review]
Nice job

**Pull request merged**
