### PR TITLE
Feature: Landing Page

### PR DESCRIPTION
**Pull request by kagaba-etienne**
#### What does this PR do?
- Creates Landing page
- Enables a seller to add images easily while creating products

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout ft-landing-page-61
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello [[Link](https://trello.com/c/9SVVL7Ov)]() (#61)

#### Screenshots (if appropriate)

Screenshot 2023-06-30 at 14 13 20

### CODE REVIEW

**Review by faid-terence — APPROVED** [review]

**Review by ALVINdimpos — APPROVED** [review]

**Review by vanessa-abewe — APPROVED** [review]

**Review by yobuir — APPROVED** [review]

**Review by chanceDira — CHANGES_REQUESTED** [review]
Latest news section is not responsive, also fix typo, it should be latest instead of lates.
We might need a footer too

**Comment by kagaba-etienne** [comment]
> Latest news section is not responsive, also fix typo, it should be latest instead of lates.
> We might need a footer too

Faid has worked on the footer, I think he is waitng for the page design to be merged so that he can append the footer.
Let me see what I can do on the latest news section!

**Comment by chanceDira** [comment]
Okay, no worries.
Fix the latest news section

**Review by chanceDira — APPROVED** [review]
Looking good

**Pull request merged**
