### PR TITLE
#23 feature: add-item-Tocart

### PR DESCRIPTION
**Pull request by vanessa-abewe**
#### What does this PR do?
--to add the item to the cart

#### Description of Task to be completed?
---to make sure  once the buyer is logged in they are able to add their desired product on their cart

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branchName
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello https://trello.com/c/mGBjs2dm

#### Screenshots (if appropriate)

### CODE REVIEW

**Review by faid-terence — APPROVED** [review]

**Review by Muhet — APPROVED** [review]
Great Job Abewe

**Review by ALVINdimpos — APPROVED** [review]

**Review by nili-alu — CHANGES_REQUESTED** [review]
nice job @Abewe, there is little change I would ask to look at it again, 
1. the page is not fitting the screen as you can see on this image
image

2. second thing as you scroll up things floating up the nav-bar, as you can see on the following image add to cart, quantity is floating up on nav-bar.
image

**Comment by vanessa-abewe** [comment]
i have made some changes ,let me know if the problem is still there

**Review by nili-alu — APPROVED** [review]

**Review by chanceDira — CHANGES_REQUESTED** [review]
Nice work @Vanessa-bitega Just one thing,
Can you put coverage in .gitignore

**Pull request closed without merging**
