### PR TITLE
#58 #20 Feature:In-app Notifications

### PR DESCRIPTION
**Pull request by ALVINdimpos**
#### What does this PR do?
This PR introduces the in-app notifications feature to notify users of important events and actions within the application. It includes displaying the notification count, allowing users to view all notifications, and implementing the functionality to mark all notifications as read.

#### Description of Task to be completed?
The task involves implementing the necessary components and logic to handle in-app notifications. This includes displaying the notification icon with the count of new and unread notifications, providing a notification panel to view all available notifications, and implementing the functionality to mark all notifications as read.

#### How should this be manually tested?
```bash 
  git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
   ```
   ```bash
   cd ecommerce-app-predators-fe
   ```
   ```bash
   git checkout ft/in-app-notification-58
   ```
   ```bash
   npm i
   ```
   ```bash
   npm run dev
   ```

#### What are the relevant pivotal tracker/Trello stories?
Trello [Link](https://trello.com/c/0KJmwvC3/58-in-app-notifications) (#-58)
Trello [Link](https://trello.com/c/baVRFvBz/20-marking-all-notifications-as-read) (#-20)

#### Screenshots (if appropriate)

### CODE REVIEW

**Review by faid-terence — APPROVED** [review]

**Review by yobuir — APPROVED** [review]

**Review by nili-alu — APPROVED** [review]
nice

**Review by NTElissa — APPROVED** [review]
good

**Review by chanceDira — APPROVED** [review]
Awesome

**Review by vanessa-abewe — APPROVED** [review]

**Comment by ALVINdimpos** [comment]
[In-app Notifications](https://trello.com/c/0KJmwvC3/58-in-app-notifications)

**Review by chanceDira — APPROVED** [review]
Looking good

**Pull request merged**
